-- Switch auth to better-auth managed tables (schema generated by its CLI,
-- adapted to uuid ids to match the domain tables' user_id columns).
-- Existing accounts and all their data are dropped.

drop table if exists sessions;

truncate decks, marketplace_decks, review_logs, marketplace_upload_requests cascade;

alter table decks drop constraint decks_user_id_fkey;
alter table marketplace_decks drop constraint marketplace_decks_user_id_fkey;
alter table marketplace_deck_instances drop constraint marketplace_deck_instances_user_id_fkey;
alter table review_logs drop constraint review_logs_user_id_fkey;
alter table marketplace_upload_requests drop constraint marketplace_upload_requests_user_id_fkey;

drop table users;

create table "user" (
	"id" uuid not null primary key,
	"name" text not null,
	"email" text not null unique,
	"emailVerified" boolean not null,
	"image" text,
	"createdAt" timestamptz default current_timestamp not null,
	"updatedAt" timestamptz default current_timestamp not null,
	-- app fields (better-auth additionalFields)
	"isAdmin" boolean default false not null,
	"pieceSet" text default 'standard' not null,
	"boardTheme" text default 'default' not null,
	"borderType" text default 'black' not null,
	"showCoordinates" boolean default true not null,
	"animationDuration" integer default 300 not null
);

create table "session" (
	"id" uuid not null primary key,
	"expiresAt" timestamptz not null,
	"token" text not null unique,
	"createdAt" timestamptz default current_timestamp not null,
	"updatedAt" timestamptz not null,
	"ipAddress" text,
	"userAgent" text,
	"userId" uuid not null references "user" ("id") on delete cascade
);

create table "account" (
	"id" uuid not null primary key,
	"accountId" text not null,
	"providerId" text not null,
	"userId" uuid not null references "user" ("id") on delete cascade,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" timestamptz,
	"refreshTokenExpiresAt" timestamptz,
	"scope" text,
	"password" text,
	"createdAt" timestamptz default current_timestamp not null,
	"updatedAt" timestamptz not null
);

create table "verification" (
	"id" uuid not null primary key,
	"identifier" text not null,
	"value" text not null,
	"expiresAt" timestamptz not null,
	"createdAt" timestamptz default current_timestamp not null,
	"updatedAt" timestamptz default current_timestamp not null
);

create index "session_userId_idx" on "session" ("userId");
create index "account_userId_idx" on "account" ("userId");
create index "verification_identifier_idx" on "verification" ("identifier");

-- every user reference cascades so better-auth's account deletion can remove
-- a user together with everything they own
alter table decks add constraint decks_user_id_fkey
	foreign key (user_id) references "user" ("id") on delete cascade;
alter table marketplace_decks add constraint marketplace_decks_user_id_fkey
	foreign key (user_id) references "user" ("id") on delete cascade;
alter table marketplace_deck_instances add constraint marketplace_deck_instances_user_id_fkey
	foreign key (user_id) references "user" ("id") on delete cascade;
alter table review_logs add constraint review_logs_user_id_fkey
	foreign key (user_id) references "user" ("id") on delete cascade;
alter table marketplace_upload_requests add constraint marketplace_upload_requests_user_id_fkey
	foreign key (user_id) references "user" ("id") on delete cascade;
