-- Full schema (pre-production: recreate the database from this file instead of
-- running incremental migrations).
--
-- Cards have a front and a back (each an ordered list of blocks). A front
-- board can additionally carry a back layer (solutionFrom/solutionAnnotations
-- inside its JSON): moves and annotations hidden in study until the card is
-- turned.

-- better-auth managed tables (schema generated by its CLI, adapted to uuid ids
-- to match the domain tables' user_id columns)
create table "user" (
	"id" uuid not null primary key,
	"name" text not null,
	"email" text not null unique,
	"emailVerified" boolean not null,
	"image" text,
	"createdAt" timestamptz default current_timestamp not null,
	"updatedAt" timestamptz default current_timestamp not null,
	-- app fields (better-auth additionalFields)
	"isAdmin" boolean default false not null,
	"pieceSet" text default 'standard' not null,
	"boardTheme" text default 'default' not null,
	"borderType" text default 'black' not null,
	"showCoordinates" boolean default true not null,
	"animationDuration" integer default 300 not null
);

create table "session" (
	"id" uuid not null primary key,
	"expiresAt" timestamptz not null,
	"token" text not null unique,
	"createdAt" timestamptz default current_timestamp not null,
	"updatedAt" timestamptz not null,
	"ipAddress" text,
	"userAgent" text,
	"userId" uuid not null references "user" ("id") on delete cascade
);

create table "account" (
	"id" uuid not null primary key,
	"accountId" text not null,
	"providerId" text not null,
	"userId" uuid not null references "user" ("id") on delete cascade,
	"accessToken" text,
	"refreshToken" text,
	"idToken" text,
	"accessTokenExpiresAt" timestamptz,
	"refreshTokenExpiresAt" timestamptz,
	"scope" text,
	"password" text,
	"createdAt" timestamptz default current_timestamp not null,
	"updatedAt" timestamptz not null
);

create table "verification" (
	"id" uuid not null primary key,
	"identifier" text not null,
	"value" text not null,
	"expiresAt" timestamptz not null,
	"createdAt" timestamptz default current_timestamp not null,
	"updatedAt" timestamptz default current_timestamp not null
);

create index "session_userId_idx" on "session" ("userId");
create index "account_userId_idx" on "account" ("userId");
create index "verification_identifier_idx" on "verification" ("identifier");

create type deck_theme as enum ('openings', 'endgames', 'tactics', 'strategy', 'checkmates');

-- every user reference cascades so better-auth's account deletion can remove
-- a user together with everything they own
create table decks (
	id uuid primary key default gen_random_uuid(),
	user_id uuid references "user" ("id") on delete cascade not null,
	name text not null,
	unique(user_id, name)
);

-- Tactic cards are graded Correct/Incorrect instead of FSRS: Correct finishes
-- the card for good (finished_at), Incorrect re-queues it a day later. They
-- carry no FSRS memory state, so the FSRS columns stay null for them (state is
-- the constraint's representative for the group).
create table cards (
	id uuid primary key default gen_random_uuid(),
	deck_id uuid references decks(id) on delete cascade not null,
	front jsonb not null,
	back jsonb,
	card_type text not null default 'basic' check (card_type in ('basic', 'tactic')),
	finished_at timestamptz,
	due timestamptz not null,
	stability numeric,
	difficulty numeric,
	elapsed_days smallint,
	scheduled_days smallint,
	reps smallint,
	lapses smallint,
	learning_steps smallint,
	state smallint check(state between 0 and 3),
	last_review timestamptz,
	constraint tactic_cards_have_no_fsrs_state check ((card_type = 'tactic') = (state is null))
);

create table marketplace_decks (
	id uuid primary key default gen_random_uuid(),
	user_id uuid references "user" ("id") on delete cascade not null,
	name text not null unique,
	description jsonb not null,
	price numeric(5,2) check(price >= 0) not null,
	theme deck_theme not null,
	image bytea not null,
	image_type text not null
);

create table marketplace_cards (
	id uuid default gen_random_uuid() primary key,
	marketplace_deck_id uuid references marketplace_decks(id) on delete cascade not null,
	front jsonb not null,
	back jsonb,
	card_type text not null default 'basic' check (card_type in ('basic', 'tactic')),
	-- position among the deck's public preview cards; null = not in the preview
	preview_order smallint
);

create table marketplace_deck_instances (
	id uuid primary key default gen_random_uuid(),
	user_id uuid references "user" ("id") on delete cascade not null,
	marketplace_deck_id uuid references marketplace_decks(id) not null
);

create table marketplace_card_instances (
	id uuid default gen_random_uuid() primary key,
	marketplace_deck_instance_id uuid references marketplace_deck_instances(id) on delete cascade not null,
	marketplace_card_id uuid references marketplace_cards(id) on delete cascade not null,
	card_type text not null default 'basic' check (card_type in ('basic', 'tactic')),
	finished_at timestamptz,
	due timestamptz not null,
	stability numeric,
	difficulty numeric,
	elapsed_days smallint,
	scheduled_days smallint,
	reps smallint,
	lapses smallint,
	learning_steps smallint,
	state smallint check(state between 0 and 3),
	last_review timestamptz,
	constraint tactic_instances_have_no_fsrs_state check ((card_type = 'tactic') = (state is null))
);

-- tactic reviews log only rating + review time (+ due when re-queued), so the
-- FSRS columns are nullable
create table review_logs (
	id uuid primary key default gen_random_uuid(),
	user_id uuid references "user" ("id") on delete cascade not null,
	card_id uuid references cards(id) on delete cascade,
	marketplace_card_instance_id uuid references marketplace_card_instances(id),
	rating smallint check(rating between 0 and 4) not null,
	state smallint check(state between 0 and 3),
	due timestamptz,
	stability numeric,
	difficulty numeric,
	elapsed_days smallint,
	last_elapsed_days smallint,
	scheduled_days smallint,
	learning_steps smallint,
	review timestamptz not null,
	check (card_id is null or marketplace_card_instance_id is null),
	check (card_id is not null or marketplace_card_instance_id is not null)
);

-- Upload requests carry the marketplace listing details (name, description,
-- price, thumbnail) and the ordered card ids chosen as the public preview;
-- approval copies everything into the marketplace tables.
create table marketplace_upload_requests (
	id uuid primary key default gen_random_uuid(),
	deck_id uuid references decks(id) on delete cascade not null,
	user_id uuid references "user" ("id") on delete cascade not null,
	name text not null,
	description jsonb not null,
	theme deck_theme not null,
	price numeric(5,2) check(price >= 0) not null,
	image bytea not null,
	image_type text not null,
	preview_card_ids uuid[] not null default '{}',
	status text check(status in ('pending', 'approved', 'rejected')) not null default 'pending',
	-- admins reject with a reason that is shown to the requester
	rejection_reason text,
	created_at timestamptz not null default now()
);
